# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 358b56fee7d9f4e85c3c733d7b6325b8218e0a5ea8028344adeffbb654edae9a6beaaae1a693a4a38f0e8cde34f2096c42032e733082f24d2cf5570e24fb0093

test:
  secret_key_base: e22cf5e776fb190dc4efa83b31ff0835d90bd5e90b1d7ef747444263b581f19a453f5bd7265621085d1de8f2ae55bd45ebb2f54832ec4a3af8ce3dcd8f9ee73f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
